# exclude vendored files
exclude: '^(lgpl-2\.1\.txt|examples/deepzoom/static/.*\.js)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '^\.github/.*\.md$'
      - id: trailing-whitespace
        exclude: '^\.github/.*\.md$'

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
      - id: pyupgrade
        name: Modernize python code
        args: ["--py36-plus"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Reorder python imports with isort

  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        name: Format python code with black
        language_version: python3
        args: ["--skip-string-normalization"]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        name: Format python code in documentation

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
